//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Web
{


    public partial class _Default
    {

        /// <summary>
        /// lblMyCustomSectionParam1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyCustomSectionParam1;

        /// <summary>
        /// lblMyCustomSectionParam2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyCustomSectionParam2;

        /// <summary>
        /// lblMyPartnerSectionPartner1_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner1_Name;

        /// <summary>
        /// lblMyPartnerSectionPartner1_Param1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner1_Param1;

        /// <summary>
        /// lblMyPartnerSectionPartner1_Param2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner1_Param2;

        /// <summary>
        /// lblMyPartnerSectionPartner2_Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner2_Name;

        /// <summary>
        /// lblMyPartnerSectionPartner2_ClientId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner2_ClientId;

        /// <summary>
        /// lblMyPartnerSectionPartner2_ClientSecret control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner2_ClientSecret;

        /// <summary>
        /// lblMyPartnerSectionPartner2_Param1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMyPartnerSectionPartner2_Param1;
    }
}
